export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const FIRESTORE_LISTENER_INIT = "FIRESTORE_LISTENER_INIT";
export const FIRESTORE_LISTENER_SET = "FIRESTORE_LISTENER_SET"; 
export const FIRESTORE_LISTENER_ERROR = "FIRESTORE_LISTENER_ERROR";
export const FIRESTORE_LISTENER_UNSET = "FIRESTORE_LISTENER_UNSET";

export const FIRESTORE_PAGINATOR_INIT = "FIRESTORE_PAGINATOR_INIT";
export const FIRESTORE_PAGINATOR_SET = "FIRESTORE_PAGINATOR_SET"; 
export const FIRESTORE_PAGINATOR_ERROR = "FIRESTORE_PAGINATOR_ERROR";
export const FIRESTORE_PAGINATOR_UNSET = "FIRESTORE_PAGINATOR_UNSET";