export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const SET_FIRESTORE_SUBSCRIBER = "SET_FIRESTORE_SUBSCRIBER";
export const UNSET_FIRESTORE_SUBSCRIBER = "UNSET_FIRESTORE_SUBSCRIBER";


// Subscriber Key
export const PROFILE_KEY = "profile";